const mockRecipes = [
  {
    id: "di1",
    title: "Grilled Lemon Chicken",
    image: "/Grilled-Lemon-Chicken-4.jpg",
    dishType: "Dinners",
    cookingTime: 45,
    occasion: "Family Dinner",
    summary: "Juicy grilled lemon chicken served with seasonal vegetables.",
    vegan: false,
    glutenFree: true,
    ingredients: ["chicken breast", "lemon", "olive oil", "garlic", "rosemary"],
    steps: [
      "Marinate the chicken in lemon juice and spices.",
      "Preheat grill to medium-high heat.",
      "Grill each side for 6-8 minutes until cooked through.",
    ],
    rating: 4.5,
    calories: 520,
    servings: 4,
    difficulty: "Medium",
    tags: ["grilled", "protein-rich", "summer"],
  },
  {
    id: "lu1",
    title: "Quinoa Veggie Bowl",
    image: "/quinoa.jpg",
    dishType: "Lunches",
    cookingTime: 30,
    occasion: "Work Lunch",
    summary: "A nourishing bowl of quinoa, roasted veggies, and hummus.",
    vegan: true,
    glutenFree: true,
    ingredients: ["quinoa", "zucchini", "carrot", "bell pepper", "hummus"],
    steps: [
      "Cook quinoa until fluffy.",
      "Roast vegetables with olive oil and spices.",
      "Assemble in a bowl with hummus topping.",
    ],
    rating: 4.8,
    calories: 430,
    servings: 2,
    difficulty: "Easy",
    tags: ["vegan", "healthy", "meal prep"],
  },
  {
    id: "br1",
    title: "Banana Oat Pancakes",
    image: "/banana-oats.jpeg",
    dishType: "Breakfasts",
    cookingTime: 20,
    occasion: "Weekend Brunch",
    summary:
      "Fluffy pancakes made from bananas and oats, perfect with maple syrup.",
    vegan: true,
    glutenFree: false,
    ingredients: ["banana", "rolled oats", "almond milk", "baking powder"],
    steps: [
      "Blend all ingredients into a batter.",
      "Cook pancakes on a non-stick pan over medium heat.",
      "Serve warm with toppings of choice.",
    ],
    rating: 4.2,
    calories: 390,
    servings: 3,
    difficulty: "Easy",
    tags: ["brunch", "dairy-free", "kid-friendly"],
  },
  {
    id: "ds1",
    title: "Chocolate Lava Cake",
    image: "/choc-cake.webp",
    dishType: "Desserts",
    cookingTime: 25,
    occasion: "Date Night",
    summary: "Rich and gooey chocolate lava cake with a molten center.",
    vegan: false,
    glutenFree: false,
    ingredients: ["dark chocolate", "butter", "eggs", "sugar", "flour"],
    steps: [
      "Melt chocolate and butter together.",
      "Mix in eggs, sugar, and flour.",
      "Bake at 200°C for 10-12 minutes until edges are firm but center is soft.",
    ],
    rating: 4.9,
    calories: 600,
    servings: 2,
    difficulty: "Hard",
    tags: ["indulgent", "romantic", "rich"],
  },
  {
    id: 16789,
    title: "Bruschetta",
    dishType: "Appetizers",
    image: "/bruschetta.webp",
    summary:
      "Grilled bread rubbed with garlic and topped with tomatoes, olive oil, and basil.",
    cookingTime: "15 mins",
    occasion: "Dinner Party",
    vegan: true,
    glutenFree: false,
    calories: 180,
    difficulty: "Easy",
    tags: ["Italian", "Fresh", "Toasted"],
    rating: 4.5,
    servings: 4,
  },
  {
    id: 2653,
    title: "Energy Bites",
    dishType: "Snacks",
    image: "/energy-bites.jpeg",
    summary:
      "No-bake energy bites made with oats, peanut butter, honey, and chocolate chips.",
    cookingTime: "10 mins",
    occasion: "Post Workout",
    vegan: false,
    glutenFree: true,
    calories: 210,
    difficulty: "Easy",
    tags: ["Healthy", "Quick", "Protein"],
    rating: 4.7,
    servings: 8,
  },
  {
    id: 3678,
    title: "Croissants",
    dishType: "Pastries",
    image: "/croissants.jpg",
    summary:
      "Buttery, flaky, and golden brown French croissants perfect for breakfast or snacks.",
    cookingTime: "2 hrs",
    occasion: "Brunch",
    vegan: false,
    glutenFree: false,
    calories: 270,
    difficulty: "Hard",
    tags: ["French", "Buttery", "Baked"],
    rating: 4.8,
    servings: 6,
  },
  {
    id: 4667,
    title: "Dukkah Spice Mix",
    dishType: "Herbs & Spices",
    image: "/dukkah.jpeg",
    summary:
      "A Middle Eastern blend of herbs, nuts, and spices served with bread and olive oil.",
    cookingTime: "5 mins",
    occasion: "Anytime",
    vegan: true,
    glutenFree: true,
    calories: 60,
    difficulty: "Easy",
    tags: ["Middle Eastern", "Nutty", "Flavorful"],
    rating: 4.6,
    servings: 10,
  },
  {
    id: 5675,
    title: "Garlic Mashed Potatoes",
    dishType: "Side Dishes",
    image: "/potatoes.png",
    summary: "Creamy mashed potatoes infused with roasted garlic and butter.",
    cookingTime: "30 mins",
    occasion: "Thanksgiving",
    vegan: false,
    glutenFree: true,
    calories: 220,
    difficulty: "Medium",
    tags: ["Comfort Food", "Creamy", "Holiday"],
    rating: 4.9,
    servings: 4,
  },
  {
    id: "di2",
    title: "Garlic Butter Salmon",
    image: "/Garlic-Butter-Salmon.webp",
    dishType: "Dinners",
    cookingTime: 25,
    occasion: "Weeknight Dinner",
    summary: "Flaky salmon fillets glazed with garlic butter and lemon.",
    vegan: false,
    glutenFree: true,
    ingredients: ["salmon fillets", "butter", "garlic", "lemon", "parsley"],
    steps: [
      "Season salmon with salt and pepper.",
      "Sear salmon skin-side down for 4 minutes.",
      "Add garlic butter sauce and bake at 190°C for 8 minutes.",
    ],
    rating: 4.7,
    calories: 450,
    servings: 2,
    difficulty: "Medium",
    tags: ["omega-3", "quick", "elegant"],
  },
  {
    id: "lu2",
    title: "Mediterranean Wrap",
    image: "/Mediterranean-Wrap.jpg",
    dishType: "Lunches",
    cookingTime: 15,
    occasion: "Picnic",
    summary: "Whole-grain wrap stuffed with hummus, veggies, and feta.",
    vegan: false,
    glutenFree: false,
    ingredients: [
      "whole-grain wrap",
      "hummus",
      "cucumber",
      "tomato",
      "feta cheese",
    ],
    steps: [
      "Spread hummus on the wrap.",
      "Layer sliced veggies and crumbled feta.",
      "Roll tightly and slice in half.",
    ],
    rating: 4.4,
    calories: 380,
    servings: 1,
    difficulty: "Easy",
    tags: ["portable", "fresh", "no-cook"],
  },
  {
    id: "br2",
    title: "Berry Smoothie Bowl",
    image: "/berry-smoothie-bowl.jpg",
    dishType: "Breakfasts",
    cookingTime: 10,
    occasion: "Summer Morning",
    summary: "Thick blended berry smoothie topped with granola and coconut.",
    vegan: true,
    glutenFree: true,
    ingredients: [
      "mixed berries",
      "banana",
      "almond milk",
      "granola",
      "coconut flakes",
    ],
    steps: [
      "Blend berries, banana, and almond milk until thick.",
      "Pour into a bowl and top with granola and coconut.",
    ],
    rating: 4.5,
    calories: 320,
    servings: 1,
    difficulty: "Easy",
    tags: ["refreshing", "antioxidants", "instagrammable"],
  },
  {
    id: "ds2",
    title: "Tiramisu",
    image: "/tiramisu.jpg",
    dishType: "Desserts",
    cookingTime: 60,
    occasion: "Dinner Party",
    summary:
      "Classic Italian dessert with coffee-soaked ladyfingers and mascarpone.",
    vegan: false,
    glutenFree: false,
    ingredients: [
      "ladyfingers",
      "espresso",
      "mascarpone",
      "cocoa powder",
      "eggs",
    ],
    steps: [
      "Dip ladyfingers in espresso and layer in a dish.",
      "Whisk mascarpone with egg yolks and sugar.",
      "Alternate layers and chill for 4 hours.",
    ],
    rating: 4.9,
    calories: 550,
    servings: 6,
    difficulty: "Hard",
    tags: ["decadent", "make-ahead", "crowd-pleaser"],
  },
  {
    id: "ap1",
    title: "Stuffed Mushrooms",
    image: "/stuffed-mushrooms.jpg",
    dishType: "Appetizers",
    cookingTime: 20,
    occasion: "Holiday Gathering",
    summary: "Mushroom caps filled with herbed cream cheese and breadcrumbs.",
    vegan: false,
    glutenFree: false,
    ingredients: [
      "cremini mushrooms",
      "cream cheese",
      "garlic",
      "parsley",
      "breadcrumbs",
    ],
    steps: [
      "Remove mushroom stems and sauté with garlic.",
      "Mix with cream cheese and herbs, then stuff caps.",
      "Bake at 180°C for 15 minutes.",
    ],
    rating: 4.3,
    calories: 200,
    servings: 8,
    difficulty: "Easy",
    tags: ["bite-sized", "savory", "festive"],
  },
  {
    id: "sn1",
    title: "Spiced Nuts",
    image: "/spiced-nuts.jpeg",
    dishType: "Snacks",
    cookingTime: 15,
    occasion: "Game Night",
    summary: "Roasted nuts tossed in smoked paprika and maple syrup.",
    vegan: true,
    glutenFree: true,
    ingredients: [
      "mixed nuts",
      "maple syrup",
      "smoked paprika",
      "cayenne",
      "sea salt",
    ],
    steps: [
      "Toss nuts with syrup and spices.",
      "Roast at 160°C for 10 minutes, stirring once.",
    ],
    rating: 4.6,
    calories: 280,
    servings: 6,
    difficulty: "Easy",
    tags: ["crunchy", "protein-packed", "addictive"],
  },
  {
    id: "pa1",
    title: "Spinach & Feta Pastry",
    image: "/spinach-pastry.webp",
    dishType: "Pastries",
    cookingTime: 35,
    occasion: "Brunch Buffet",
    summary: "Flaky puff pastry filled with spinach and feta cheese.",
    vegan: false,
    glutenFree: false,
    ingredients: ["puff pastry", "spinach", "feta", "onion", "egg wash"],
    steps: [
      "Sauté spinach and onions, then mix with feta.",
      "Fill pastry squares, fold, and brush with egg wash.",
      "Bake at 200°C until golden.",
    ],
    rating: 4.7,
    calories: 310,
    servings: 4,
    difficulty: "Medium",
    tags: ["flaky", "savory", "Mediterranean"],
  },
  {
    id: "hs1",
    title: "Za'atar Seasoning",
    image: "/zaatar.jpg",
    dishType: "Herbs & Spices",
    cookingTime: 5,
    occasion: "Anytime",
    summary: "Middle Eastern spice blend with thyme, sumac, and sesame seeds.",
    vegan: true,
    glutenFree: true,
    ingredients: ["dried thyme", "sumac", "sesame seeds", "salt"],
    steps: [
      "Mix all ingredients in a jar.",
      "Sprinkle on bread, salads, or roasted veggies.",
    ],
    rating: 4.8,
    calories: 20,
    servings: 12,
    difficulty: "Easy",
    tags: ["versatile", "aromatic", "pantry-staple"],
  },
  {
    id: "sd1",
    title: "Honey Glazed Carrots",
    image: "/glazed-carrots.jpg",
    dishType: "Side Dishes",
    cookingTime: 20,
    occasion: "Sunday Roast",
    summary: "Tender carrots caramelized with honey and thyme.",
    vegan: false,
    glutenFree: true,
    ingredients: ["carrots", "honey", "butter", "thyme", "salt"],
    steps: [
      "Sauté carrots in butter until tender.",
      "Add honey and thyme, cook until glazed.",
    ],
    rating: 4.4,
    calories: 180,
    servings: 4,
    difficulty: "Easy",
    tags: ["sweet", "colorful", "kid-friendly"],
  },
  {
    id: "di3",
    title: "Beef Bourguignon",
    image: "/beef-bourguignon.avif",
    dishType: "Dinners",
    cookingTime: 180,
    occasion: "Special Occasion",
    summary: "French beef stew slow-cooked in red wine with mushrooms.",
    vegan: false,
    glutenFree: true,
    ingredients: [
      "beef chuck",
      "red wine",
      "mushrooms",
      "pearl onions",
      "bacon",
    ],
    steps: [
      "Sear beef and bacon in a Dutch oven.",
      "Deglaze with wine, add veggies, and simmer for 2.5 hours.",
    ],
    rating: 4.9,
    calories: 620,
    servings: 6,
    difficulty: "Hard",
    tags: ["hearty", "classic", "winter"],
  },
  {
    id: "ds3",
    title: "Mango Sticky Rice",
    image: "/mango-rice.webp",
    dishType: "Desserts",
    cookingTime: 40,
    occasion: "Summer Treat",
    summary: "Thai dessert with sweet coconut rice and fresh mango.",
    vegan: true,
    glutenFree: true,
    ingredients: [
      "sticky rice",
      "coconut milk",
      "mango",
      "sugar",
      "sesame seeds",
    ],
    steps: [
      "Steam rice and mix with coconut milk and sugar.",
      "Serve with sliced mango and a drizzle of coconut sauce.",
    ],
    rating: 4.7,
    calories: 420,
    servings: 3,
    difficulty: "Medium",
    tags: ["tropical", "creamy", "exotic"],
  },
  {
    id: "di4",
    title: "Miso Glazed Eggplant",
    image: "/miso-eggplant.jpg",
    dishType: "Dinners",
    cookingTime: 30,
    occasion: "Vegetarian Night",
    summary: "Silky roasted eggplant with sweet-savory miso glaze.",
    vegan: true,
    glutenFree: true,
    ingredients: [
      "eggplant",
      "white miso paste",
      "mirin",
      "sesame oil",
      "scallions",
    ],
    steps: [
      "Slice eggplant and score the flesh.",
      "Brush with miso-mirin glaze and roast at 200°C for 25 mins.",
      "Garnish with sesame seeds and scallions.",
    ],
    rating: 4.6,
    calories: 290,
    servings: 2,
    difficulty: "Medium",
    tags: ["umami", "Japanese", "caramelized"],
  },
  {
    id: "lu3",
    title: "Soba Noodle Salad",
    image: "/soba-salad.jpg",
    dishType: "Lunches",
    cookingTime: 20,
    occasion: "Meal Prep",
    summary:
      "Chilled buckwheat noodles with sesame dressing and crisp veggies.",
    vegan: true,
    glutenFree: false,
    ingredients: [
      "soba noodles",
      "cucumber",
      "red pepper",
      "edamame",
      "sesame dressing",
    ],
    steps: [
      "Cook soba noodles and rinse under cold water.",
      "Toss with julienned veggies and dressing.",
      "Top with toasted sesame seeds.",
    ],
    rating: 4.5,
    calories: 380,
    servings: 2,
    difficulty: "Easy",
    tags: ["refreshing", "nutty", "light"],
  },
  {
    id: "br3",
    title: "Shakshuka",
    image: "/shakshuka.webp",
    dishType: "Breakfasts",
    cookingTime: 25,
    occasion: "Weekend Brunch",
    summary: "Eggs poached in spiced tomato-pepper sauce.",
    vegan: false,
    glutenFree: true,
    ingredients: [
      "eggs",
      "tomatoes",
      "bell pepper",
      "onion",
      "cumin",
      "paprika",
    ],
    steps: [
      "Sauté onions and peppers until soft.",
      "Add tomatoes and spices, simmer for 10 mins.",
      "Create wells for eggs, cover until whites set.",
    ],
    rating: 4.8,
    calories: 350,
    servings: 3,
    difficulty: "Medium",
    tags: ["North African", "hearty", "one-pan"],
  },
  {
    id: "ds4",
    title: "Panna Cotta",
    image: "/panna-cotta.jpg",
    dishType: "Desserts",
    cookingTime: 240,
    occasion: "Dinner Party",
    summary: "Italian custard with vanilla bean and berry compote.",
    vegan: false,
    glutenFree: true,
    ingredients: [
      "heavy cream",
      "sugar",
      "gelatin",
      "vanilla bean",
      "mixed berries",
    ],
    steps: [
      "Bloom gelatin in cold water.",
      "Heat cream with sugar and vanilla, then mix in gelatin.",
      "Chill for 4 hours and top with compote.",
    ],
    rating: 4.9,
    calories: 420,
    servings: 4,
    difficulty: "Medium",
    tags: ["silky", "elegant", "make-ahead"],
  },
  {
    id: "ap2",
    title: "Prosciutto-Wrapped Asparagus",
    image: "/prosciutto-asparagus.jpg",
    dishType: "Appetizers",
    cookingTime: 15,
    occasion: "Cocktail Party",
    summary: "Crisp asparagus spears wrapped in salty prosciutto.",
    vegan: false,
    glutenFree: true,
    ingredients: ["asparagus", "prosciutto", "olive oil", "lemon zest"],
    steps: [
      "Trim asparagus and blanch for 2 mins.",
      "Wrap each spear with prosciutto.",
      "Bake at 190°C for 8 mins until crisp.",
    ],
    rating: 4.7,
    calories: 180,
    servings: 6,
    difficulty: "Easy",
    tags: ["low-carb", "elegant", "quick"],
  },
  {
    id: "sn2",
    title: "Kale Chips",
    image: "/kale-chips.jpg",
    dishType: "Snacks",
    cookingTime: 20,
    occasion: "Healthy Snack",
    summary: "Crispy baked kale leaves with nutritional yeast.",
    vegan: true,
    glutenFree: true,
    ingredients: [
      "kale",
      "olive oil",
      "nutritional yeast",
      "garlic powder",
      "salt",
    ],
    steps: [
      "Tear kale into pieces and toss with oil.",
      "Sprinkle with seasonings and bake at 150°C for 15 mins.",
    ],
    rating: 4.2,
    calories: 120,
    servings: 2,
    difficulty: "Easy",
    tags: ["crunchy", "guilt-free", "nutrient-dense"],
  },
  {
    id: "pa2",
    title: "Apple Turnovers",
    image: "/apple-turnovers.jpg",
    dishType: "Pastries",
    cookingTime: 35,
    occasion: "Autumn Breakfast",
    summary: "Flaky puff pastry filled with cinnamon-spiced apples.",
    vegan: false,
    glutenFree: false,
    ingredients: [
      "puff pastry",
      "apples",
      "cinnamon",
      "brown sugar",
      "egg wash",
    ],
    steps: [
      "Sauté apples with sugar and cinnamon.",
      "Fill pastry squares, fold, and brush with egg wash.",
      "Bake at 200°C until golden.",
    ],
    rating: 4.6,
    calories: 320,
    servings: 4,
    difficulty: "Medium",
    tags: ["flaky", "aromatic", "cozy"],
  },
  {
    id: "hs2",
    title: "Chili Oil",
    image: "/chili-oil.jpeg",
    dishType: "Herbs & Spices",
    cookingTime: 10,
    occasion: "Pantry Staple",
    summary: "Infused oil with crushed chilies and Szechuan peppercorns.",
    vegan: true,
    glutenFree: true,
    ingredients: [
      "neutral oil",
      "dried chilies",
      "Szechuan peppercorns",
      "garlic",
      "star anise",
    ],
    steps: [
      "Heat oil to 180°C.",
      "Pour over crushed spices and let steep for 1 hour.",
      "Strain and store.",
    ],
    rating: 4.8,
    calories: 50,
    servings: 20,
    difficulty: "Easy",
    tags: ["spicy", "versatile", "umami"],
  },
  {
    id: "sd2",
    title: "Crispy Brussels Sprouts",
    image: "/brussels.jpeg",
    dishType: "Side Dishes",
    cookingTime: 25,
    occasion: "Holiday Dinner",
    summary: "Roasted Brussels sprouts with balsamic glaze.",
    vegan: true,
    glutenFree: true,
    ingredients: [
      "Brussels sprouts",
      "balsamic vinegar",
      "honey",
      "pecans",
      "olive oil",
    ],
    steps: [
      "Toss sprouts with oil, salt, and pepper.",
      "Roast at 220°C for 20 mins until crispy.",
      "Drizzle with balsamic reduction and pecans.",
    ],
    rating: 4.5,
    calories: 210,
    servings: 4,
    difficulty: "Easy",
    tags: ["caramelized", "festive", "nutty"],
  },
  {
    id: "di5",
    title: "Lobster Risotto",
    image: "/lobster.webp",
    dishType: "Dinners",
    cookingTime: 45,
    occasion: "Anniversary Dinner",
    summary: "Creamy Arborio rice with lobster tail and saffron.",
    vegan: false,
    glutenFree: true,
    ingredients: [
      "lobster tail",
      "Arborio rice",
      "white wine",
      "saffron",
      "parmesan",
    ],
    steps: [
      "Sauté rice in butter until translucent.",
      "Deglaze with wine and slowly add stock.",
      "Fold in cooked lobster meat and saffron.",
    ],
    rating: 4.9,
    calories: 580,
    servings: 2,
    difficulty: "Hard",
    tags: ["luxury", "special-occasion", "creamy"],
  },
  {
    id: "br4",
    title: "Avocado Toast with Poached Egg",
    image: "/avocado-toast.jpeg",
    dishType: "Breakfasts",
    cookingTime: 15,
    occasion: "Quick Morning",
    summary: "Crunchy toast topped with creamy avocado and a runny egg.",
    vegan: false,
    glutenFree: false,
    ingredients: ["bread", "avocado", "egg", "lemon juice", "chili flakes"],
    steps: [
      "Toast the bread slices.",
      "Mash avocado with lemon juice and spread on toast.",
      "Top with a poached egg and sprinkle chili flakes.",
    ],
    rating: 4.6,
    calories: 340,
    servings: 2,
    difficulty: "Easy",
    tags: ["brunch", "simple", "healthy"],
  },
  {
    id: "lu4",
    title: "Quinoa Buddha Bowl",
    image: "/quinoa-bowl.jpg",
    dishType: "Lunches",
    cookingTime: 25,
    occasion: "Plant-Based Meal",
    summary: "Wholesome bowl of quinoa, veggies, and tahini dressing.",
    vegan: true,
    glutenFree: true,
    ingredients: ["quinoa", "chickpeas", "spinach", "carrots", "tahini"],
    steps: [
      "Cook quinoa and season lightly.",
      "Roast chickpeas and prep raw veggies.",
      "Assemble bowl and drizzle with tahini dressing.",
    ],
    rating: 4.7,
    calories: 410,
    servings: 2,
    difficulty: "Easy",
    tags: ["balanced", "fiber-rich", "Instagram-worthy"],
  },
  {
    id: "ds6",
    title: "Molten Lava Cake",
    image: "/lava-cake.jpg",
    dishType: "Desserts",
    cookingTime: 25,
    occasion: "Romantic Dinner",
    summary: "Warm chocolate cake with gooey molten center.",
    vegan: false,
    glutenFree: false,
    ingredients: ["dark chocolate", "butter", "eggs", "sugar", "flour"],
    steps: [
      "Melt chocolate with butter.",
      "Whisk eggs and sugar, fold in flour and chocolate.",
      "Bake for 12 minutes and serve warm.",
    ],
    rating: 4.9,
    calories: 460,
    servings: 2,
    difficulty: "Medium",
    tags: ["rich", "decadent", "date-night"],
  },
  {
    id: "ap3",
    title: "Caprese Skewers",
    image: "/caprese-skewers.webp",
    dishType: "Appetizers",
    cookingTime: 10,
    occasion: "Garden Party",
    summary: "Cherry tomatoes, mozzarella, and basil drizzled with balsamic.",
    vegan: false,
    glutenFree: true,
    ingredients: [
      "mozzarella balls",
      "cherry tomatoes",
      "basil",
      "balsamic glaze",
      "toothpicks",
    ],
    steps: [
      "Skewer tomato, mozzarella, and basil.",
      "Drizzle with balsamic glaze.",
      "Serve immediately or chill slightly.",
    ],
    rating: 4.5,
    calories: 150,
    servings: 6,
    difficulty: "Easy",
    tags: ["Italian", "bite-size", "colorful"],
  },
  {
    id: "sn3",
    title: "Hummus & Veggie Cups",
    image: "/hummus-cups.jpeg",
    dishType: "Snacks",
    cookingTime: 10,
    occasion: "Snack Platter",
    summary: "Individual cups filled with hummus and crunchy vegetable sticks.",
    vegan: true,
    glutenFree: true,
    ingredients: ["hummus", "carrot", "cucumber", "celery", "bell pepper"],
    steps: [
      "Portion hummus into small cups.",
      "Add assorted veggie sticks upright.",
      "Garnish with paprika if desired.",
    ],
    rating: 4.4,
    calories: 130,
    servings: 4,
    difficulty: "Easy",
    tags: ["portable", "fresh", "low-calorie"],
  },
  {
    id: "pa3",
    title: "Mini Spinach Feta Puffs",
    image: "/spinach-puffs.jpeg",
    dishType: "Pastries",
    cookingTime: 30,
    occasion: "Brunch Bites",
    summary: "Golden puff pastry filled with spinach and tangy feta.",
    vegan: false,
    glutenFree: false,
    ingredients: ["puff pastry", "spinach", "feta", "garlic", "egg wash"],
    steps: [
      "Sauté spinach and garlic, mix with crumbled feta.",
      "Fill pastry squares and fold into triangles.",
      "Brush with egg wash and bake until golden.",
    ],
    rating: 4.7,
    calories: 260,
    servings: 4,
    difficulty: "Medium",
    tags: ["flaky", "savory", "Greek-inspired"],
  },
  {
    id: "hs3",
    title: "Lemon Herb Salt",
    image: "/lemon-salt.jpg",
    dishType: "Herbs & Spices",
    cookingTime: 5,
    occasion: "Pantry Boost",
    summary: "Zesty homemade salt blend with herbs and lemon zest.",
    vegan: true,
    glutenFree: true,
    ingredients: ["sea salt", "lemon zest", "rosemary", "thyme"],
    steps: [
      "Mix all ingredients and pulse in a food processor.",
      "Spread to dry or store in an airtight jar.",
      "Use for seasoning meats or veggies.",
    ],
    rating: 4.3,
    calories: 0,
    servings: 30,
    difficulty: "Easy",
    tags: ["zesty", "fragrant", "versatile"],
  },
  {
    id: "sd3",
    title: "Garlic Mashed Cauliflower",
    image: "/cauliflower-mash.jpg",
    dishType: "Side Dishes",
    cookingTime: 20,
    occasion: "Low-Carb Dinner",
    summary: "Creamy mashed cauliflower with roasted garlic.",
    vegan: true,
    glutenFree: true,
    ingredients: [
      "cauliflower",
      "garlic",
      "olive oil",
      "nutritional yeast",
      "salt",
    ],
    steps: [
      "Steam cauliflower until soft.",
      "Blend with roasted garlic, oil, and seasonings.",
      "Serve hot with optional herbs.",
    ],
    rating: 4.6,
    calories: 170,
    servings: 4,
    difficulty: "Easy",
    tags: ["keto", "creamy", "comforting"],
  },
  {
    id: "di6",
    title: "Stuffed Bell Peppers",
    image: "/stuffed-peppers.jpg",
    dishType: "Dinners",
    cookingTime: 40,
    occasion: "Family Dinner",
    summary: "Baked peppers filled with rice, beans, and spices.",
    vegan: true,
    glutenFree: true,
    ingredients: [
      "bell peppers",
      "rice",
      "black beans",
      "tomato sauce",
      "onion",
    ],
    steps: [
      "Sauté filling ingredients until combined.",
      "Stuff into halved peppers and bake at 190°C for 25 mins.",
      "Garnish with herbs or avocado.",
    ],
    rating: 4.6,
    calories: 370,
    servings: 3,
    difficulty: "Medium",
    tags: ["hearty", "budget-friendly", "meal-prep"],
  },
  {
    id: "ds7",
    title: "Coconut Mango Chia Pudding",
    image: "/chia-pudding.jpeg",
    dishType: "Desserts",
    cookingTime: 180,
    occasion: "Tropical Treat",
    summary: "Layered chia pudding with coconut milk and mango puree.",
    vegan: true,
    glutenFree: true,
    ingredients: [
      "chia seeds",
      "coconut milk",
      "mango",
      "maple syrup",
      "vanilla",
    ],
    steps: [
      "Mix chia seeds with coconut milk and sweetener.",
      "Chill for 3 hours until set.",
      "Top with blended mango and serve cold.",
    ],
    rating: 4.7,
    calories: 300,
    servings: 2,
    difficulty: "Easy",
    tags: ["refreshing", "tropical", "dairy-free"],
  },
];

export default mockRecipes;
